on: [push]

jobs:
  release_the_17g_website:
    runs-on: ubuntu-latest
    name: build and release for the 17g website
    steps:
      - name: Setup Node.js 10.x 
        uses: actions/setup-node@v2
        with:
          node-version: "14" 
        
      - name: Install hexo and gitbook
        run: |
          npm install hexo-cli -g
          npm install -g gitbook-cli

      - name: Checkout main source
        uses: actions/checkout@v2
      
      - name: Checkout all books source
        working-directory: ${{ github.workspace }}/../
        run: |
          /usr/bin/git clone https://github.com/wangwei1237/chaos-engineering.git --depth 1
          /usr/bin/git clone https://github.com/wangwei1237/digital_video_concepts.git --depth 1
          /usr/bin/git clone https://github.com/wangwei1237/temperature-of-the-idioms.git --depth 1  
          /usr/bin/git clone https://github.com/wangwei1237/monolith-to-microservices.git --depth 1
          /usr/bin/git clone https://github.com/wangwei1237/discovery-the-unpredictable-risk.git --depth 1
          /usr/bin/git clone https://github.com/wangwei1237/Kubernetes-in-Action-Second-Edition.git --depth 1

      - name: build the main website
        working-directory: ${{ github.workspace }}
        run: |
          npm install 
          /bin/cp -rf misc/bilibili-embed-convert/* node_modules/bilibili-embed-convert/
          /bin/cp -rf misc/hexo-asset-image_index.js node_modules/hexo-asset-image/index.js
          /bin/cp -rf misc/markdown-it-katex_index.js node_modules/@abreto/markdown-it-katex/index.js
          hexo clean && hexo generate

      - name: build the books
        working-directory: ${{ github.workspace }}/../
        run: | 
          cp wangwei1237.github.io_src/build_books.sh .
          /bin/bash ./build_books.sh "${{ github.workspace }}/../"
      
      - name: release the website
        working-directory: ${{ github.workspace }}
        run: |
          /bin/bash ./release.sh "${{ github.workspace }}/../"

      #- name: deploy the website
      #  uses: sma11black/hexo-action@v1.0.4
      #  with:
      #    deploy_key: ${{ secrets.DEPLOY_KEY }}
      #    user_name: Wang Wei
      #    user_email: wangwei1237@gmail.com
      #    commit_msg: ${{ github.event.head_commit.message }}
      - name: deploy the website for github
        working-directory: ${{ github.workspace }}
        run: |
          /usr/bin/git clone https://github.com/wangwei1237/wangwei1237.github.io.git --depth 1
          cd wangwei1237.github.io && cp -r ${{ github.workspace }}/public/* .
          git config --global user.email "wangwei1237@gmail.com"
          git config --global user.name "Wang Wei"
          git add . && git commit -m "${{ github.event.head_commit.message }}"
          git push https://wangwei1237:${{ secrets.DEPLOY_GITHUB_TOKEN }}@github.com/wangwei1237/wangwei1237.github.io.git master

      - name: deploy the website for gitee
        working-directory: ${{ github.workspace }}
        run: |
          git config --global http.postBuffer 1048576000
          sudo -E apt-get -yq install ccache gnutls-bin
          /usr/bin/git clone https://oauth2:${{ secrets.DEPLOY_GITEE_TOKEN }}@gitee.com/wangwei1237/wangwei1237.git --depth 1
          cd wangwei1237 && cp -r ${{ github.workspace }}/public/* .
          git config --global user.email "wangwei1237@gmail.com"
          git config --global user.name "Wang Wei"
          git add . && git commit -m "${{ github.event.head_commit.message }}"
          git push https://wangwei1237:${{ secrets.DEPLOY_GITEE_TOKEN }}@gitee.com/wangwei1237/wangwei1237.git master



